name: Deploy Gophish with ngrok

on:
  push:
    branches:
      - main  # Cambia a tu rama principal si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t gophish-app .

    - name: Run Gophish container
      run: |
        docker run -d \
          --name gophish \
          -p 3333:3333 \
          -p 80:80 \
          gophish-app

    - name: Install ngrok
      run: |
        sudo curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update
        sudo apt install -y ngrok

    - name: Authenticate ngrok
      run: |
        echo ${{ secrets.NGROK_AUTH_TOKEN }} | ngrok authtoken

    - name: Start ngrok
      run: |
        ngrok http 3333 > /tmp/ngrok.log &
        sleep 10  # Espera a que ngrok esté listo
        cat /tmp/ngrok.log
        curl --silent --fail http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    - name: Check Gophish status
      run: |
        curl --silent --fail http://localhost:80 || exit 1
        curl --silent --fail https://localhost:3333 || exit 1
