name: Deploy Gophish to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia a tu rama principal si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t gophish-app .

    - name: Run Gophish container
      run: |
        docker run -d \
          --name gophish \
          -p 3333:3333 \
          -p 80:80 \
          gophish-app

    - name: Wait for Gophish to start
      run: sleep 30  # Ajusta el tiempo según sea necesario

    - name: Copy static files
      run: |
        docker cp gophish:/app/static ./static

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./static