name: Deploy Gophish

on:
  push:
    branches:
      - main  # Cambia a tu rama principal si es diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t gophish-app .

    - name: Run Gophish container
      run: |
        docker run -d \
          --name gophish \
          -p 3333:3333 \
          -p 80:80 \
          gophish-app

    - name: Wait for Gophish to be ready
      run: |
        sleep 30  # Ajusta el tiempo si es necesario

    - name: Check Gophish status
      run: |
        curl --silent --fail http://localhost:80 || exit 1
        curl --silent --fail https://localhost:3333 || exit 1
